org: flyosprey
app: aws-python-rest-api
service: aws-python-rest-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: blobs-bucket
    BlobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: blob_id
            AttributeType: S
          - AttributeName: callback_url
            AttributeType: S
        KeySchema:
          - AttributeName: blob_id
            KeyType: HASH
          - AttributeName: callback_url
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  tableName: Blobs
  s3Sync:
    - bucketName: blobs-bucket
      localDir: UploadData

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /blobs
          method: POST
      - http:
          path: /blobs/{blob_id}
          method: GET
